### ISSUE TITLE
ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by spacedmonkey** [Yoast/PHPUnit-Polyfills#45] opened 2021-07-09 14:10 UTC
Running PHPUnit 6.5.14 in PHP 7.4, generate the following error when using `createMock` 

```
Function ReflectionType::__toString() is deprecated
```

I wonder if this library could patch this issue. 

PHPUnit issue https://github.com/sebastianbergmann/phpunit/issues/3728

**Comment by spacedmonkey** [comment] 2021-07-09 14:21
For more context, here is the PR where I found the issue https://github.com/google/web-stories-wp/pull/8264

It seems to be an issue, with methods having return type hints + reflection.

**Comment by jrfnl** [comment] 2021-07-09 19:42
@spacedmonkey This is not an issue which this library will or should fix, as it is an issue caused by a wrong test setup configuration.

The whole point of the polyfills is that you can use the modern, PHPUnit 9.x assertions and expectations (and fix the `void` issue), but can still run your tests on the most appropriate (and supported) PHPUnit version for the PHP version on which you are running the tests.

In short: you should not be running PHPUnit 6.x on PHP 7.4. You should be using PHPUnit 8.x or 9.x, which are both supported for PHP 7.4. You could even use PHPUnit 7.x, which will also fix this, even though not officially supported on PHP 7.4.

![image](https://user-images.githubusercontent.com/663378/125127001-39bcff80-e0fc-11eb-99c1-957f6e90db50.png)
Source: https://phpunit.de/supported-versions.html

Looking at the repo you linked to, there are two things I can see:
1. You have a committed `composer.lock` file via which you are managing your dependencies, including your `dev` dependencies like PHPUnit.
2. You are running tests in the context of WordPress, which limits the test running to PHPUnit 5.x - 7.x.

To fix this with that context in mind:
* Either "lock" PHPUnit at PHPUnit 7.x and downgrade the PHPUnit version in your CI script for the test run against PHP 7.0.
* Or keep the lock at PHPUnit 6.x and upgrade the PHPUnit version in your CI script for any test runs on PHP >= 7.4.

To limit the update to just PHPUnit (and its dependencies), you can use a pattern like so (for the second option listed above):
```yaml
composer require --dev phpunit/phpunit:"^7.5" --update-with-dependencies --ignore-platform-reqs
```

You're basically now trying to fit a square block into a round hole.

**Comment by jrfnl** [comment] 2021-07-14 05:33
@spacedmonkey Just checking: did my answer clarify things enough for you ? Can this issue be closed ?

**Comment by jrfnl** [comment] 2021-07-28 20:11
Closing for lack of reply.

**Closed by jrfnl** 2021-07-28 20:11 UTC
Labels: Status: wontfix

**Comment by spacedmonkey** [comment] 2021-07-28 20:17
We worked around this issues, but patching PHPUnit 6.x to run in PHP 7.4. It makes everything a lot simpler, as means we can run PHP 6.x everywhere and it just works.

**Comment by jrfnl** [comment] 2021-07-28 20:26
I presume you mean PHPUnit 6.x ? PHP 6.x was never released.

Either way, glad you got it working, but I still think you are trying to fit a square block into a round hole and that's not what this package will help you do.
